---
- name: Deploy Radarr (Movies)
  community.docker.docker_container:
    name: radarr
    image: "lscr.io/linuxserver/radarr:{{ versions.radarr }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network }}"
    env:
      PUID: "{{ puid | string}}"
      PGID: "{{ pgid | string}}"
      TZ: "{{ timezone }}"
    ports:
      - "{{ ports.radarr }}:7878"
    volumes:
      - "{{ paths.docker_data }}/radarr:/config"
      - "/mnt/d/data:/data"
